const PERMS = require("./permission");

/**
 * Defines permissions which are trigger permissions, if trigger permission found permission defined will 
 * auto added to that permission of role
 */


//tenant
const TENANT_UPDATE = [PERMS.TENANT_GET_ALL_DATA];

//role
const ROLE_GET_ALL_WITH_PERM = [PERMS.ROLE_GET_ALL];
const ROLE_GET_MEMBER_ROLES_WITH_PERM = [
	PERMS.ROLE_GET_MEMBER_ROLES,
	PERMS.ROLE_GET_MEMBER_PERM_COMBINED,
];
const ROLE_GET_MEMBER_PERM_COMBINED = [PERMS.ROLE_GET_MEMBER_ROLES];
const ROLE_CREATE = [PERMS.ROLE_GET_ALL, PERMS.ROLE_GET_ALL_WITH_PERM];
const ROLE_UPDATE = [PERMS.ROLE_GET_ALL, PERMS.ROLE_GET_ALL_WITH_PERM];

const ROLE_ASSIGN_REMOVE = [
	PERMS.ROLE_GET_ALL,
	PERMS.ROLE_GET_ALL_WITH_PERM,
	PERMS.ROLE_GET_MEMBER_ROLES,
	PERMS.ROLE_GET_MEMBER_ROLES_WITH_PERM,
];

module.exports = {
	TENANT_UPDATE,
	ROLE_GET_ALL_WITH_PERM,
	ROLE_GET_MEMBER_ROLES_WITH_PERM,
	ROLE_GET_MEMBER_PERM_COMBINED,
	ROLE_CREATE,
	ROLE_UPDATE,
	ROLE_ASSIGN_REMOVE,
};
