const PERMS = require("./permission");

module.exports = {
	TENANT_UPDATE: [PERMS.TENANT_GET_ALL_DATA],
	ROLE_GET_ALL_WITH_PERM: [PERMS.ROLE_GET_ALL],
	ROLE_GET_MEMBER_ROLES_WITH_PERM: [
		PERMS.ROLE_GET_MEMBER_ROLES,
		PERMS.ROLE_GET_MEMBER_PERM_COMBINED,
	],
    ROLE_GET_MEMBER_PERM_COMBINED:[PERMS.ROLE_GET_MEMBER_ROLES],
    ROLE_CREATE:[
        PERMS.ROLE_GET_ALL,
        PERMS.ROLE_GET_ALL_WITH_PERM
    ],
};
