
const PERMS = {

  //all perms
  TENANT_OWNER_PERMS:'TENANT_OWNER_PERMS',
  TENANT_CO_OWNER_PERMS:'TENANT_CO_OWNER_PERMS',

  // Tenant
  TENANT_LOGIN:'TENANT_LOGIN',
  TENANT_GET_ALL_DATA: 'TENANT_GET_ALL_DATA',
  TENANT_GET_MODERATED_DATA:'TENANT_GET_MODERATED_DATA',
  TENANT_UPDATE: 'TENANT_UPDATE',
  TENANT_DEACTIVATE: 'TENANT_DEACTIVATE',
  TENANT_DELETE: 'TENANT_DELETE',

  // Role
  ROLE_GET_ALL: 'ROLE_GET_ALL',
  ROLE_GET_ALL_WITH_PERM: 'ROLE_GET_ALL_WITH_PERM',
  ROLE_GET_MODERATED_DETAILS:'ROLE_GET_MODERATED_DETAILS',
  ROLE_GET_DETAILS: 'ROLE_GET_DETAILS',
  ROLE_GET_DETAILS_WITH_PERM: 'ROLE_GET_DETAILS_WITH_PERM',
  ROLE_GET_MEMBER_ROLES: 'ROLE_GET_MEMBER_ROLES',
  ROLE_GET_MEMBER_ROLES_WITH_PERM: 'ROLE_GET_MEMBER_ROLES_WITH_PERM',
  ROLE_GET_MEMBER_PERM_COMBINED: 'ROLE_GET_MEMBER_PERM_COMBINED',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_ASSIGN_REMOVE: 'ROLE_ASSIGN_REMOVE',
  ROLE_DELETE: 'ROLE_DELETE',

  // Tenant Member
  TENANT_MEMBER_GET_ALL: 'TENANT_MEMBER_GET_ALL',
  TENANT_MEMBER_GET_DETAILS: 'TENANT_MEMBER_GET_DETAILS',
  TENANT_MEMBER_GET_DETAILS_SELF: 'TENANT_MEMBER_GET_DETAILS_SELF',
  TENANT_MEMBER_SEND_INVITE_TENANT: 'TENANT_MEMBER_SEND_INVITE_TENANT',
  TENANT_MEMBER_SEND_INVITE_PLATFORM: 'TENANT_MEMBER_SEND_INVITE_PLATFORM',
  TENANT_MEMBER_UPDATE: 'TENANT_MEMBER_UPDATE',
  TENANT_MEMBER_UPDATE_SELF: 'TENANT_MEMBER_UPDATE_SELF',
  TENANT_MEMBER_REMOVE: 'TENANT_MEMBER_REMOVE',

  // Product
  PRODUCT_GET_ALL: 'PRODUCT_GET_ALL',
  PRODUCT_GET_DETAILS: 'PRODUCT_GET_DETAILS',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',
  PRODUCT_PIN:"PRODUCT_PIN",


  // Category
  CATEGORY_GET_ALL: 'CATEGORY_GET_ALL',
  CATEGORY_PIN:'CATEGORY_PIN',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',

  // Sale
  SALE_GET_ALL: 'SALE_GET_ALL',
  SALE_GET_SELF:'SALE_GET_SELF',
  SALE_CREATE: 'SALE_CREATE',
  SALE_CREATE_SELF: 'SALE_CREATE_SELF',
  SALE_UPDATE: 'SALE_UPDATE',
  SALE_UPDATE_SELF: 'SALE_UPDATE_SELF',
  SALE_DELETE: 'SALE_DELETE',
  SALE_DELETE_SELF: 'SALE_DELETE_SELF',


  // Customer
  CUSTOMER_GET_ALL: 'CUSTOMER_GET_ALL',
  CUSTOMER_GET_SELF:'CUSTOMER_GET_SELF',
  CUSTOMER_CREATE: 'CUSTOMER_CREATE',
  CUSTOMER_CREATE_SELF:'CUSTOMER_CREATE_SELF',
  CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
  CUSTOMER_UPDATE_SELF:'CUSTOMER_UPDATE_SELF',
  CUSTOMER_DELETE: 'CUSTOMER_DELETE',
  CUSTOMER_DELETE_SELF:'CUSTOMER_DELETE_SELF',

  // Supply
  SUPPLY_GET_ALL: 'SUPPLY_GET_ALL',
  SUPPLY_BULK_IMPORT: 'SUPPLY_BULK_IMPORT',
  SUPPLY_UPDATE: 'SUPPLY_UPDATE',
  SUPPLY_DELETE: 'SUPPLY_DELETE',

  // Notification
  NOTIFICATION_GET_SELF: 'NOTIFICATION_GET_SELF',

  // Activity
  ACTIVITY_GET_ALL: 'ACTIVITY_GET_ALL',

  // Request  
  REQUEST_GET_TENANT_ALL:'REQUEST_GET_ALL',
  REQUEST_GET_TENANT_SELF:'REQUEST_GET_TENANT_SELF',

  REQUEST_SEND_TENANT_INVITE: 'REQUEST_SEND_TENANT_INVITE',
  REQUEST_CANCEL_TENANT_INVITE:'REQUEST_CANCEL_TENANT_INVITE',
  REQUEST_CANCEL_SELF_TENANT_INVITE:'REQUEST_CANCEL_TENANT_INVITE',

  REQUEST_SEND_PLATFORM_INVITE: 'REQUEST_SEND_PLATFORM_INVITE',
  REQUEST_CANCEL_PLATFORM_INVITE:'REQUEST_CANCEL_PLATFORM_INVITE',
  REQUEST_CANCEL_SELF_PLATFORM_INVITE:'REQUEST_CANCEL_PLATFORM_INVITE_SELF'
};

module.exports = PERMS;
