// src/constants/permissions.js
const PERMS = {
  // Tenant
  TENANT_GET_ALL_DATA: 'TENANT_GET_ALL_DATA',
  TENANT_UPDATE: 'TENANT_UPDATE',
  TENANT_DEACTIVATE: 'TENANT_DEACTIVATE',
  TENANT_DELETE: 'TENANT_DELETE',

  // Role
  ROLE_GET_ALL: 'ROLE_GET_ALL',
  ROLE_GET_ALL_WITH_PERM: 'ROLE_GET_ALL_WITH_PERM',
  ROLE_GET_DETAILS: 'ROLE_GET_DETAILS',
  ROLE_GET_DETAILS_WITH_PERM: 'ROLE_GET_DETAILS_WITH_PERM',
  ROLE_GET_USER_ROLE: 'ROLE_GET_USER_ROLE',
  ROLE_GET_USER_ROLE_WITH_PERM: 'ROLE_GET_USER_ROLE_WITH_PERM',
  ROLE_GET_USER_PERM_COMBINED: 'ROLE_GET_USER_PERM_COMBINED',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_ASSIGN: 'ROLE_ASSIGN',
  ROLE_REMOVE: 'ROLE_REMOVE',
  ROLE_DELETE: 'ROLE_DELETE',

  // Tenant Member
  TENANT_MEMBER_GET_ALL: 'TENANT_MEMBER_GET_ALL',
  TENANT_MEMBER_GET_DETAILS: 'TENANT_MEMBER_GET_DETAILS',
  TENANT_MEMBER_SEND_INVITE_TENANT: 'TENANT_MEMBER_SEND_INVITE_TENANT',
  TENANT_MEMBER_SEND_INVITE_PLATFORM: 'TENANT_MEMBER_SEND_INVITE_PLATFORM',
  TENANT_MEMBER_UPDATE: 'TENANT_MEMBER_UPDATE',
  TENANT_MEMBER_UPDATE_SELF: 'TENANT_MEMBER_UPDATE_SELF',
  TENANT_MEMBER_REMOVE: 'TENANT_MEMBER_REMOVE',

  // Product
  PRODUCT_GET_ALL: 'PRODUCT_GET_ALL',
  PRODUCT_GET_DETAILS: 'PRODUCT_GET_DETAILS',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',

  // Category
  CATEGORY_GET_ALL: 'CATEGORY_GET_ALL',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',

  // Sale
  SALE_GET_ALL: 'SALE_GET_ALL',
  SALE_CREATE: 'SALE_CREATE',
  SALE_UPDATE: 'SALE_UPDATE',
  SALE_DELETE: 'SALE_DELETE',

  // Customer
  CUSTOMER_GET_ALL: 'CUSTOMER_GET_ALL',
  CUSTOMER_CREATE: 'CUSTOMER_CREATE',
  CUSTOMER_UPDATE: 'CUSTOMER_UPDATE',
  CUSTOMER_DELETE: 'CUSTOMER_DELETE',

  // Supply
  SUPPLY_GET_ALL: 'SUPPLY_GET_ALL',
  SUPPLY_BULK_IMPORT: 'SUPPLY_BULK_IMPORT',
  SUPPLY_UPDATE: 'SUPPLY_UPDATE',
  SUPPLY_DELETE: 'SUPPLY_DELETE',

  // Notification
  NOTIFICATION_GET_MINE: 'NOTIFICATION_GET_MINE',

  // Activity
  ACTIVITY_GET_ALL: 'ACTIVITY_GET_ALL',

  // Request
  REQUEST_SEND: 'REQUEST_SEND',
  REQUEST_ACCEPT: 'REQUEST_ACCEPT',
  REQUEST_REJECT: 'REQUEST_REJECT'
};

module.exports = PERMS;
