//constants
const PERMS = require("./permission");

module.exports = {
	//Restricted perms
	RESTRICTED_PERMS: [PERMS.TENANT_DEACTIVATE, PERMS.TENANT_DELETE],

	//tenant perms
	TENANT_LOGIN_PERMS: [PERMS.TENANT_LOGIN],
	TENANT_GET_ALL_DATA_PERMS: [PERMS.TENANT_LOGIN, PERMS.TENANT_GET_ALL_DATA],
	TENANT_UPDATE_PERMS: [
		PERMS.TENANT_LOGIN,
		PERMS.TENANT_GET_ALL_DATA,
		PERMS.TENANT_UPDATE,
	],

	//tenant roles perms
	ROLE_GET_ALL_PERMS: [PERMS.TENANT_LOGIN, PERMS.ROLE_GET_ALL],
	ROLE_GET_ALL_WITH_PERMS: [
		PERMS.TENANT_LOGIN,
		PERMS.ROLE_GET_ALL,
		PERMS.ROLE_GET_ALL_WITH_PERM,
	],
	//
	ROLE_GET_DETAILS_PERMS: [PERMS.TENANT_LOGIN, PERMS.ROLE_GET_DETAILS],
	ROLE_GET_DETAILS_WITH_PERMS: [
		PERMS.TENANT_LOGIN,
		PERMS.ROLE_GET_DETAILS,
		PERMS.ROLE_GET_DETAILS_WITH_PERM,
	],
	//
	ROLE_GET_MEMBER_ROLES_PERMS: [
		PERMS.TENANT_LOGIN,
		PERMS.ROLE_GET_MEMBER_ROLES,
	],
	ROLE_GET_MEMBER_ROLES_WITH_PERM: [
		PERMS.TENANT_LOGIN,
		PERMS.ROLE_GET_MEMBER_ROLES,
		PERMS.ROLE_GET_MEMBER_ROLES_WITH_PERM,
		PERMS.ROLE_GET_MEMBER_PERM_COMBINED,
	],
	//
	ROLE_GET_MEMBER_PERM_COMBINED_PERMS: [
		PERMS.TENANT_LOGIN,
		PERMS.ROLE_GET_MEMBER_ROLES,
		PERMS.ROLE_GET_MEMBER_PERM_COMBINED,
	],
	ROLE_CREATE_PERMS: [
		PERMS.TENANT_LOGIN,
		PERMS.ROLE_GET_ALL,
		PERMS.ROLE_GET_ALL_WITH_PERM,
		PERMS.ROLE_CREATE,
	],
};
