//constants
const PERMS = require("./permission");

module.exports = {
    //Restricted perms
    RESTRICTED_PERMS:[PERMS.TENANT_DEACTIVATE,PERMS.TENANT_DELETE],


    TENANT_LOGIN_PERMS:[PERMS.TENANT_LOGIN,PERMS.TENANT_GET_MODERATED_DATA],

    TENANT_GET_ALL_DATA_PERMS:[PERMS.TENANT_LOGIN,PERMS.TENANT_GET_ALL_DATA],
    TENANT_UPDATE_PERMS:[PERMS.TENANT_LOGIN,PERMS.TENANT_UPDATE]
    
}