//constants
const PERMS = require("./permission.js");

//preset
const ROLE_PRESETS = {
	OWNER: [PERMS.TENANT_OWNER_PERMS],
	CO_OWNER:[PERMS.TENANT_CO_OWNER_PERMS],

	ADMIN: [
		// Tenant (no deactivate/delete by default)
		PERMS.TENANT_GET_ALL_DATA,
		PERMS.TENANT_UPDATE,
		PERMS.TENANT_LOGIN,

		// Role (manage but no delete by default; adjust if you want)
		PERMS.ROLE_GET_ALL,
		PERMS.ROLE_GET_ALL_WITH_PERM,
		PERMS.ROLE_GET_DETAILS,
		PERMS.ROLE_GET_DETAILS_WITH_PERM,
		PERMS.ROLE_GET_USER_ROLE,
		PERMS.ROLE_GET_USER_ROLE_WITH_PERM,
		PERMS.ROLE_GET_USER_PERM_COMBINED,
		PERMS.ROLE_CREATE,
		PERMS.ROLE_UPDATE,
		PERMS.ROLE_ASSIGN,
		PERMS.ROLE_REMOVE,

		// Tenant Member
		PERMS.TENANT_MEMBER_GET_ALL,
		PERMS.TENANT_MEMBER_GET_DETAILS,
		PERMS.TENANT_MEMBER_SEND_INVITE_TENANT,
		PERMS.TENANT_MEMBER_UPDATE,

		// Product
		PERMS.PRODUCT_GET_ALL,
		PERMS.PRODUCT_GET_DETAILS,
		PERMS.PRODUCT_CREATE,
		PERMS.PRODUCT_UPDATE,
		PERMS.PRODUCT_DELETE,

		// Category
		PERMS.CATEGORY_GET_ALL,
		PERMS.CATEGORY_CREATE,
		PERMS.CATEGORY_UPDATE,
		PERMS.CATEGORY_DELETE,

		// Sale
		PERMS.SALE_GET_ALL,
		PERMS.SALE_CREATE,
		PERMS.SALE_UPDATE,
		PERMS.SALE_DELETE,

		// Customer
		PERMS.CUSTOMER_GET_ALL,
		PERMS.CUSTOMER_CREATE,
		PERMS.CUSTOMER_UPDATE,
		PERMS.CUSTOMER_DELETE,

		// Supply
		PERMS.SUPPLY_GET_ALL,
		PERMS.SUPPLY_BULK_IMPORT,
		PERMS.SUPPLY_UPDATE,
		PERMS.SUPPLY_DELETE,

		// Misc
		PERMS.NOTIFICATION_GET_MINE,
		PERMS.ACTIVITY_GET_ALL,
		PERMS.REQUEST_SEND,
		PERMS.REQUEST_ACCEPT,
		PERMS.REQUEST_REJECT,
	],

	STAFF: [
		// Tenant: view only
		PERMS.TENANT_GET_MODERATED_DATA,
		PERMS.TENANT_LOGIN,

		// Roles: view
		PERMS.ROLE_GET_USER_ROLE,
		PERMS.ROLE_GET_MODERATED_DETAILS,
        PERMS.ROLE_GET_USER_PERM_COMBINED,

		// Members: view and self-update
		PERMS.TENANT_MEMBER_UPDATE_SELF,
        PERMS.TENANT_MEMBER_GET_DETAILS_SELF,

		// Product: full CRUD except delete (optional)
		PERMS.PRODUCT_GET_ALL,
		PERMS.PRODUCT_GET_DETAILS,

		// Category: view and create (optional)
		PERMS.CATEGORY_GET_ALL,

		// Sale: create/update
		PERMS.SALE_GET_MINE,
		PERMS.SALE_CREATE_MINE,
		PERMS.SALE_UPDATE_MINE,

		// Customer: create/update
		PERMS.CUSTOMER_GET_MINE,
		PERMS.CUSTOMER_CREATE_MINE,
		PERMS.CUSTOMER_UPDATE_MINE,

		// Supply: list and bulk import
		PERMS.SUPPLY_GET_ALL,

		// Misc
		PERMS.NOTIFICATION_GET_MINE,
		PERMS.REQUEST_SEND,
	],  
	
	MEMBER:[
		PERMS.TENANT_GET_MODERATED_DATA,
		PERMS.ROLE_GET_MODERATED_DETAILS,
		PERMS.TENANT_LOGIN
	]
};

module.exports = ROLE_PRESETS
