module.exports = {
	OTP_TYPE: {
		VERIFY_CREDENTIAL: "VERIFY-CREDENTIAL",
		FORGOT_PASSWORD: "FORGOT-PASSWORD",
	},
	SESSION_OTP_TYPE: {
		REGISTRATION: "REGISTRATION-SESSION",
		FORGOT_PASSWORD: "FORGOT-PASSWORD-SESSION",
	},
	MESSAGE_TYPE: {
		//tenant
		TENANT_DEACTIVATED_MSG: "TENANT-DEACTIVATED-MAIL",
		TENANT_DELETED_MSG: "TENANT-DELETED-MSG",

		//invite
		PLATFORM_AND_TENANT_INVITE:"PLATFORM-AND-TENANT-INVITE",
		TENANT_INVITE:"TENANT-INVITE",
		//user
		USER_DEACTIVATED_MSG: "USER-DEACTIVATED-MSG"
	},

};
