module.exports = {
	OTP_TYPE: {
		VERIFY_CREDENTIAL: "VERIFY-CREDENTIAL",
		FORGOT_PASSWORD: "FORGOT-PASSWORD",
	},
	SESSION_OTP_TYPE: {
		REGISTRATION: "REGISTRATION-SESSION",
		FORGOT_PASSWORD: "FORGOT-PASSWORD-SESSION",
	},
	MESSAGE_TYPE: {
		TENANT_DEACTIVATED_MSG: "TENANT-DEACTIVATED-MAIL",
		TENANT_DELETED_MSG: "TENANT-DELETED-MSG",
		USER_DEACTIVATED_MSG: "USER_DEACTIVATED_MSG"
	},
};
